name: 'pascal5i_deeplabv3_fold_3_bn_freeze_backbone'
task: 'few_shot_semantic_segmentation_fine_tuning'
input_dim: (3, 512, 512)
num_classes: 16
meta_training_num_classes: 16 # (15 annotated class in splitted training set + 1 background)
meta_testing_num_classes: 2
save_model: True

SYSTEM:
  use_cpu: False
  num_workers: 16

BACKBONE:
  network: 'deeplabv3_resnet101'
  pooling: False
  use_pretrained: True
  pretrained_path: "/data/trained_weights/discriminative_deeplab_resnet101_no_last_relu.pth"

CLASSIFIER:
  classifier: "seg_cos"
  SEGHEAD:
    use_bilinear_interpolation: True
    COSINE:
      weight_norm: False
      train_scale_factor: 10
      val_scale_factor: 3

LOSS:
  loss: 'semantic_nllloss'

DATASET:
  dataset: 'pascal_5i'
  PASCAL5i:
    folding: 3
  TRANSFORM:
    TRAIN:
      transforms: ('normalize', )
      joint_transforms: ('joint_naive_resize', 'joint_random_horizontal_flip')
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.485, 0.456, 0.406)
          sd: (0.229, 0.224, 0.225)
        crop_size: (512, 512)
    TEST:
      transforms: ('normalize', )
      joint_transforms: ('joint_naive_resize', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.485, 0.456, 0.406)
          sd: (0.229, 0.224, 0.225)
        crop_size: (512, 512)

TRAIN:
  max_epochs: 30
  batch_size: 24
  initial_lr: 0.1
  lr_scheduler: "polynomial"
  freeze_backbone: True
  step_down_gamma: 0.1
  step_down_on_epoch: [50, 80]
  log_interval: 20
  OPTIMIZER:
    type: "SGD"
    momentum: 0.9
    weight_decay: 1e-4

META_TEST:
  shot: 1

TEST:
  batch_size: 1
