name: 'pascal5i_semantic_segmentation_vgg16_no_bn_COS_HEAD_metatrain'
task: 'few_shot_semantic_segmentation_fine_tuning'
input_dim: (3, 417, 417)
meta_training_num_classes: 16 # (15 annotated class in splitted training set + 1 background)
meta_testing_num_classes: 2
save_model: True

SYSTEM:
  use_cpu: False
  num_workers: 16

BACKBONE:
  network: 'vgg16_seg'
  pooling: False
  use_pretrained: True
  pretrained_path: "/data/pretrained_model/vgg16-397923af.pth"

CLASSIFIER:
  classifier: "fcn32s_cos"
  SEGHEAD:
    use_bilinear_interpolation: True
    COSINE:
      weight_norm: False
      train_scale_factor: 40
      val_scale_factor: 3

LOSS:
  loss: 'semantic_nllloss'

DATASET:
  dataset: 'pascal_5i'
  PASCAL5i:
    folding: 0
  cache_all_data: True
  TRANSFORM:
    TRAIN:
      transforms: ('normalize', )
      joint_transforms: ('joint_random_crop', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.4700, 0.4468, 0.4076)
          sd: (0.2439, 0.2390, 0.2420)
        crop_size: (417, 417)
    TEST:
      transforms: ('normalize', )
      joint_transforms: ('joint_random_crop', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.4700, 0.4468, 0.4076)
          sd: (0.2439, 0.2390, 0.2420)
        crop_size: (417, 417)

TRAIN:
  max_epochs: 40
  batch_size: 16
  initial_lr: 1e-3
  lr_scheduler: "step_down"
  step_down_gamma: 0.1
  step_down_on_epoch: [15, 25, 35]
  log_interval: 20
  OPTIMIZER:
    type: "SGD"
    momentum: 0.9
    weight_decay: 1e-5

META_TEST:
  shot: 5

TEST:
  batch_size: 1
