name: 'voc2012_semantic_segmentation_refinenet_lw50_fold_1'
task: 'few_shot_semantic_segmentation_fine_tuning'
input_dim: (3, 417, 417)
meta_training_num_classes: 16 # (15 annotated class in splitted training set + 1 background)
meta_testing_num_classes: 2
save_model: True

SYSTEM:
  num_workers: 16

BACKBONE:
  network: 'refinenet_lw50'
  pooling: False
  use_pretrained: True
  pretrained_path: "/data/pretrained_model/resnet50-19c8e357.pth"

CLASSIFIER:
  classifier: "seg_cos"

LOSS:
  loss: 'semantic_nllloss'

DATASET:
  dataset: 'pascal_5i'
  PASCAL5i:
    folding: 1
  cache_all_data: True
  TRANSFORM:
    TRAIN:
      transforms: ('normalize', )
      joint_transforms: ('joint_naive_resize', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.485, 0.456, 0.406)
          sd: (0.229, 0.224, 0.225)
        crop_size: (417, 417)
    TEST:
      transforms: ('normalize', )
      joint_transforms: ('joint_naive_resize', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.485, 0.456, 0.406)
          sd: (0.229, 0.224, 0.225)
        crop_size: (417, 417)

TRAIN:
  max_epochs: 130
  batch_size: 8
  initial_lr: 5e-4
  lr_scheduler: "step_down"
  step_down_gamma: 0.1
  step_down_on_epoch: [100, 120]
  log_interval: 20
  OPTIMIZER:
    type: "SGD"
    momentum: 0.9
    weight_decay: 1e-5

META_TEST:
  shot: 1

TEST:
  batch_size: 1
