name: 'voc2012_semantic_segmentation_refinenet_lw50'
task: 'semantic_segmentation'
input_dim: (3, 224, 224)
num_classes: 21 # (20 annotated class + 1 background)
save_model: True

SYSTEM:
  use_cpu: False
  num_workers: 16

BACKBONE:
  network: 'refinenet_lw50'
  pooling: False
  use_pretrained: True
  pretrained_path: "/data/pretrained_model/resnet50-19c8e357.pth"

CLASSIFIER:
  classifier: "plain_c1"

LOSS:
  loss: 'semantic_nllloss'

DATASET:
  dataset: 'VOC2012_seg'
  cache_all_data: True
  TRANSFORM:
    TRAIN:
      transforms: ('normalize', )
      joint_transforms: ('joint_naive_resize', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.4700, 0.4468, 0.4076)
          sd: (0.2439, 0.2390, 0.2420)
        crop_size: (500, 500)
    TEST:
      transforms: ('normalize', )
      joint_transforms: ('joint_naive_resize', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.4700, 0.4468, 0.4076)
          sd: (0.2439, 0.2390, 0.2420)
        crop_size: (500, 500)

TRAIN:
  max_epochs: 180
  batch_size: 8
  initial_lr: 5e-4
  lr_scheduler: "step_down"
  step_down_gamma: 0.1
  step_down_on_epoch: [100, 150]
  log_interval: 20
  OPTIMIZER:
    type: "SGD"
    momentum: 0.9
    weight_decay: 1e-5


TEST:
  batch_size: 1
