name: 'voc2012_semantic_segmentation_vgg16_no_bn'
task: 'semantic_segmentation'
input_dim: (3, 224, 224)
num_classes: 21 # (20 annotated class + 1 background)
save_model: True

SYSTEM:
  use_cpu: False
  num_workers: 16

BACKBONE:
  network: 'vgg16'
  pooling: False
  use_pretrained: True
  pretrained_path: "/data/pretrained_model/vgg16-397923af.pth"

CLASSIFIER:
  classifier: "c1"

LOSS:
  loss: 'semantic_nllloss'

DATASET:
  dataset: 'VOC2012_seg'
  TRANSFORM:
    TRAIN:
      transforms: ('normalize', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.4700, 0.4468, 0.4076)
          sd: (0.2439, 0.2390, 0.2420)
    TEST:
      transforms: ('normalize', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.4700, 0.4468, 0.4076)
          sd: (0.2439, 0.2390, 0.2420)

TRAIN:
  max_epochs: 100
  batch_size: 1
  initial_lr: 5e-4
  lr_scheduler: "step_down"
  step_down_gamma: 0.1
  step_down_on_epoch: [30, 60, 90]
  log_interval: 500
  OPTIMIZER:
    type: "SGD"
    momentum: 0.9
    weight_decay: 1e-4


TEST:
  batch_size: 1