name: 'pytorch_cifar10_simple_mlp_dataset_test'
task: 'classification'
input_dim: (3, 32, 32)
num_classes: 10
save_model: False

SYSTEM:
  use_cpu: false

BACKBONE:
  network: 'mlp'

CLASSIFIER:
  classifier: "softmax"

LOSS:
  loss: 'cross_entropy'

DATASET:
  dataset: 'cifar10'
  TRANSFORM:
    TRAIN:
      transforms: ('random_crop', 'random_horizontal_flip')
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.1307,)
          sd: (0.3081,)
    TEST:
      transforms: ('none', )

TRAIN:
  max_epochs: 14
  batch_size: 64
  initial_lr: 1.0
  lr_scheduler: "step_down"
  step_down_gamma: 0.7
  step_down_on_epoch: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


TEST:
  batch_size: 1000