name: 'cifar10_lenet'
task: 'classification'
input_dim: (3, 32, 32)
num_classes: 10
save_model: False

SYSTEM:
  use_cpu: False

BACKBONE:
  network: 'lenet'

CLASSIFIER:
  classifier: "fc"
  FC:
    bias: False
    hidden_layers: (128, )

LOSS:
  loss: 'nll_loss'

DATASET:
  dataset: 'cifar10'
  TRANSFORM:
    TRAIN:
      transforms: ('random_crop', 'random_horizontal_flip')
    TEST:
      transforms: ('none', )

TRAIN:
  max_epochs: 14
  batch_size: 64
  initial_lr: 1.0
  lr_scheduler: "step_down"
  step_down_gamma: 0.7
  step_down_on_epoch: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


TEST:
  batch_size: 1000