name: 'scannet_25k_semantic_segmentation_vgg16_no_bn'
task: 'semantic_segmentation'
input_dim: (3, 224, 224)
num_classes: 41 # (40 annotated class + 1 background)
save_model: True

SYSTEM:
  use_cpu: False
  num_workers: 16

BACKBONE:
  network: 'vgg16_seg'
  pooling: False
  use_pretrained: True
  pretrained_path: "/data/pretrained_model/vgg16-397923af.pth"

CLASSIFIER:
  classifier: "fcn32s"

LOSS:
  loss: 'semantic_nllloss'

DATASET:
  dataset: 'scannet_25k'
  TRANSFORM:
    TRAIN:
      transforms: ('normalize', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.4700, 0.4468, 0.4076)
          sd: (0.2439, 0.2390, 0.2420)
    TEST:
      transforms: ('normalize', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.4700, 0.4468, 0.4076)
          sd: (0.2439, 0.2390, 0.2420)

TRAIN:
  max_epochs: 50
  batch_size: 1
  initial_lr: 1e-3
  lr_scheduler: "step_down"
  step_down_gamma: 0.5
  step_down_on_epoch: [15, 18, 21, 24, 27, 30]
  log_interval: 100
  OPTIMIZER:
    type: "SGD"
    momentum: 0.9
    weight_decay: 1e-5


TEST:
  batch_size: 1
