name: 'scannet_25k_semantic_segmentation_refinenet'
task: 'semantic_segmentation'
input_dim: (3, 240, 320)
num_classes: 21 # (40 annotated class + 1 background)
save_model: True

SYSTEM:
  num_workers: 16

BACKBONE:
  network: 'refinenet_lw50'
  pooling: False
  use_pretrained: True
  pretrained_path: "/data/pretrained_model/resnet50-19c8e357.pth"

CLASSIFIER:
  classifier: "seg_cos"

LOSS:
  loss: 'semantic_nllloss'

DATASET:
  dataset: 'scannet_25k'
  TRANSFORM:
    TRAIN:
      transforms: ('normalize', )
      joint_transforms: ('joint_random_scale_crop', 'joint_random_horizontal_flip')
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.4700, 0.4468, 0.4076)
          sd: (0.2439, 0.2390, 0.2420)
        crop_size: (240, 320)
    TEST:
      transforms: ('normalize', )
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.4700, 0.4468, 0.4076)
          sd: (0.2439, 0.2390, 0.2420)
        crop_size: (240, 320)
TRAIN:
  max_epochs: 50
  batch_size: 16
  initial_lr: 1e-3
  lr_scheduler: "polynomial"
  log_interval: 100
  OPTIMIZER:
    type: "SGD"
    momentum: 0.9
    weight_decay: 1e-4

TEST:
  batch_size: 1
