name: 'mini_imagenet_protonet_resnet18_w_bg'
task: 'classification'
input_dim: (3, 224, 224)
num_classes: 64
save_model: True

META_TEST:
  shot: 5

SYSTEM:
  num_workers: 12

BACKBONE:
  network: 'resnet18'
  pooling: True

LOSS:
  loss: 'cross_entropy'

DATASET:
  dataset: 'mini_imagenet'
  TRANSFORM:
    TRAIN:
      transforms: ('random_resized_crop', 'color_jitter', 'random_horizontal_flip', 'normalize')
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.485, 0.456, 0.406) # normalization parameters from https://github.com/wyharveychen/CloserLookFewShot/blob/master/data/datamgr.py
          sd: (0.229, 0.224, 0.225)
        crop_size: (224, 224)
        resize_size: (224, 224)
    TEST:
      transforms: ('resize_and_center_crop', 'normalize')
      TRANSFORMS_DETAILS:
        NORMALIZE:
          mean: (0.485, 0.456, 0.406)
          sd: (0.229, 0.224, 0.225)
        crop_size: (224, 224)
        resize_size: (224, 224)

TRAIN:
  max_epochs: 400
  batch_size: 16
  initial_lr: 0.001
  lr_scheduler: "step_down"
  log_interval: 200
  step_down_gamma: 0.1
  step_down_on_epoch: [10000]
  OPTIMIZER:
    type: "ADAM"
    weight_decay: 0.0

TEST:
  batch_size: 64